import { createClient } from 'npm:@supabase/supabase-js@2.112.4'
const db=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}})
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type,x-hradnik-enrich-key','Access-Control-Allow-Methods':'POST,OPTIONS','Content-Type':'application/json'}
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:CORS})
const clean=(v:any)=>String(v??'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim()
const norm=(s='')=>clean(s).toLocaleLowerCase('cs-CZ').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim()
const slug=(s='')=>norm(s).replace(/\s+/g,'-')
async function sourceKey(){const {data}=await db.from('hradnik_enrich_control').select('enrich_key').eq('id',true).maybeSingle();return data?.enrich_key||Deno.env.get('HRADNIK_ENRICH_KEY')||''}
async function get(url:string,ms=20000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{headers:{'User-Agent':'Hradnik/1.0 (+https://hradnik.vercel.app)'} ,signal:c.signal});if(!r.ok)return null;return await r.text()}catch{return null}finally{clearTimeout(t)}}
async function wikiTitle(lang:string,title:string){try{const u=`https://${lang}.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(title.replace(/ /g,'_'))}`;const h=await get(u);if(!h)return null;const j=JSON.parse(h);const e=clean(j.extract);return e.length>=70?{text:e,url:j.content_urls?.desktop?.page||`https://${lang}.wikipedia.org/wiki/${encodeURIComponent(title.replace(/ /g,'_'))}`,source:`${lang==='cs'?'Česká':lang.toUpperCase()} Wikipedie`,confidence:0.94}:null}catch{return null}}
async function wikiSearch(lang:string,name:string,kind:string){try{const q=new URLSearchParams({action:'query',list:'search',srnamespace:'0',srlimit:'5',format:'json',srsearch:`${name} ${kind}`});const h=await get(`https://${lang}.wikipedia.org/w/api.php?${q}`);if(!h)return null;const j=JSON.parse(h);for(const x of j.query?.search||[]){const r=await wikiTitle(lang,x.title);if(r)return r}}catch{}return null}
async function npuDirect(url:string){if(!/pamatkovykatalog\.cz/i.test(url))return null;const h=await get(url,25000);if(!h)return null;const meta=h.match(/<meta[^>]+(?:name|property)=["'](?:description|og:description)["'][^>]+content=["']([^"']+)["']/i)?.[1];if(meta&&clean(meta).length>=70)return{text:clean(meta),url,source:'NPÚ – Památkový katalog',confidence:0.98};return null}
async function npuSearch(name:string){const u=`https://www.pamatkovykatalog.cz/uskp/podle-relevance/1/seznam/?h=${encodeURIComponent(name)}&hObj=1&fulltext`;const h=await get(u,25000);if(!h)return null;const links=[...h.matchAll(/href=["']([^"']+)["']/gi)].map(x=>x[1]);for(const x of links){const url=x.startsWith('http')?x:`https://www.pamatkovykatalog.cz${x.startsWith('/')?x:`/${x}`}`;if(/pamatkovykatalog\.cz\//i.test(url)&&!/\/uskp\//i.test(url)){const r=await npuDirect(url);if(r)return r}}return null}
function extractHtml(h:string){const meta=h.match(/<meta[^>]+(?:name|property)=["'](?:description|og:description)["'][^>]+content=["']([^"']+)["']/i)?.[1];if(meta&&clean(meta).length>=70)return clean(meta);const main=h.match(/<main[^>]*>([\s\S]*?)<\/main>/i)?.[1]||h.match(/<article[^>]*>([\s\S]*?)<\/article>/i)?.[1]||h;const parts=main.split(/(?<=[.!?])\s+(?=[A-ZÁČĎÉĚÍŇÓŘŠŤÚŮÝŽ])/).map(clean).filter(x=>x.length>=90&&x.length<=1800&&!/^(Hrady|Zámky|Tvrze|Ubytování|Fotogalerie|Kontakty|Mapa|Menu|Přihlášení|Nastavení|Vyhledávání|Úvod)$/i.test(x));return parts[0]||null}
async function hrady(name:string,kind:string){const n=slug(name),k=norm(kind);const cs=k.includes('zřícen')?[`zricenina-${n}`,`hrad-${n}`,`zamek-${n}`]:k.includes('zám')?[`zamek-${n}`,`hrad-${n}`]:k.includes('tvrz')?[`tvrz-${n}`,`hrad-${n}`]:[`hrad-${n}`,`zricenina-${n}`,`zamek-${n}`,`tvrz-${n}`];for(const c of cs){const url=`https://www.hrady.cz/${c}`;const h=await get(url);if(!h)continue;const e=extractHtml(h);if(e)return{text:e,url,source:'Hrady.cz',confidence:0.9}}return null}
async function hradyZriceniny(name:string){const n=slug(name);for(const p of ['hrad','zamek','tvrz']){const url=`https://www.hrady-zriceniny.cz/${p}_${n}.htm`;const h=await get(url);if(!h)continue;const e=extractHtml(h);if(e)return{text:e,url,source:'Hrady-zříceniny.cz',confidence:0.88}}return null}
async function stored(id:number){const {data}=await db.from('hradnik_place_sources').select('source_key,source_url,source_label,raw_data,confidence').eq('place_id',id).eq('is_active',true).order('confidence',{ascending:false}).limit(20);for(const s of data||[]){const r=s.raw_data||{};for(const k of ['description','short_description','summary','extract','content','text','popis','anotace']){const e=clean(r?.[k]);if(e.length>=70)return{text:e,url:s.source_url||null,source:s.source_label||s.source_key||'Doplňkový zdroj',confidence:Number(s.confidence)||0.8}}}return null}
function fallback(p:any){const bits=[`${p.name} je historický objekt typu ${clean(p.kind||'historické místo').toLocaleLowerCase('cs-CZ')}.`,clean(p.character)?`Charakter objektu: ${clean(p.character)}.`:'',clean(p.municipality||p.district||p.region)?`Nachází se v lokalitě ${[p.municipality,p.district,p.region].map(clean).filter(Boolean).join(', ')}.`:''];return bits.filter(Boolean).join(' ')}
async function enrich(p:any){let r:any=null;if(p.source_url&&/pamatkovykatalog\.cz/i.test(p.source_url))r=await npuDirect(p.source_url);if(!r)r=await npuSearch(p.name);let sitelinks:any=null;if(p.wikidata_id){try{const h=await get(`https://www.wikidata.org/wiki/Special:EntityData/${p.wikidata_id}.json`);if(h)sitelinks=JSON.parse(h).entities?.[p.wikidata_id]}catch{}}const links=sitelinks?.sitelinks||{};if(!r&&links.cswiki?.title)r=await wikiTitle('cs',links.cswiki.title);if(!r)r=await wikiSearch('cs',p.name,p.kind||'historické místo');if(!r)for(const lang of ['en','de','pl']){const t=links?.[`${lang}wiki`]?.title;if(t){r=await wikiTitle(lang,t);if(r)break}}if(!r)for(const lang of ['en','de','pl']){r=await wikiSearch(lang,p.name,p.kind||'historical place');if(r)break}if(!r)r=await hrady(p.name,p.kind||'');if(!r)r=await hradyZriceniny(p.name);if(!r)r=await stored(p.id);const text=r?.text||clean(p.description)||fallback(p);const source=r?.source||(clean(p.description)?'Původní zdroj':'Hradník – automatický základ');const confidence=r?.confidence??(clean(p.description)?0.65:0.4);const status=confidence>=0.8?'enriched':'fallback';const {error}=await db.from('hradnik_places').update({info_summary:text,info_source:source,info_source_url:r?.url||p.source_url||null,info_updated_at:new Date().toISOString(),info_status:status,info_confidence:confidence,updated_at:new Date().toISOString()}).eq('id',p.id);if(error)throw error;return{name:p.name,status,source,confidence}}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('',{status:204,headers:CORS});if(req.method!=='POST')return json({ok:true,service:'hradnik-enrich-v4'});const k=await sourceKey();if(k&&req.headers.get('x-hradnik-enrich-key')!==k)return json({error:'Unauthorized'},401);try{const body=await req.json().catch(()=>({}));const limit=Math.min(10,Math.max(1,Number(body.limit)||5));const {data:a,error:ea}=await db.from('hradnik_places').select('id,name,kind,character,municipality,district,region,description,source_url,wikidata_id,info_status,info_updated_at').eq('is_visible',true).eq('is_current',true).eq('info_status','pending').order('id').limit(limit);if(ea)throw ea;let rows=[...(a||[])];if(rows.length<limit){const {data:b}=await db.from('hradnik_places').select('id,name,kind,character,municipality,district,region,description,source_url,wikidata_id,info_status,info_updated_at').eq('is_visible',true).eq('is_current',true).eq('info_status','fallback').lt('info_updated_at',new Date(Date.now()-7*86400000).toISOString()).order('id').limit(limit-rows.length);rows.push(...(b||[]))}const out=[];for(const p of rows){try{out.push(await enrich(p))}catch(e){out.push({name:p.name,status:'error',error:String(e)})}}return json({ok:true,processed:out.length,enriched:out.filter(x=>x.status==='enriched').length,fallback:out.filter(x=>x.status==='fallback').length,results:out})}catch(e){return json({error:String(e)},500)}})
