import { createClient } from '@supabase/supabase-js'
const URL=Deno.env.get('SUPABASE_URL')!
const KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
const db=createClient(URL,KEY,{auth:{persistSession:false}})
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,content-type','Access-Control-Allow-Methods':'POST,OPTIONS','Content-Type':'application/json'}
const json=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:CORS})
const sha256=async(s:string)=>new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))
const b64=(b:Uint8Array)=>{let s='';for(const x of b)s+=String.fromCharCode(x);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
async function user(req:Request){const h=req.headers.get('authorization')||'';if(!h.toLowerCase().startsWith('bearer '))return null;const token=h.slice(7).trim();if(!token)return null;const th=b64(await sha256(token));const {data}=await db.from('hradnik_sessions').select('user_id,expires_at,hradnik_users(id,username,display_name,role)').eq('token_hash',th).gt('expires_at',new Date().toISOString()).maybeSingle();const u=(data as any)?.hradnik_users;if(!u)return null;return u.role==='admin'?{...u,token}:null}
const text=(v:any)=>v==null?'':String(v).trim()
const num=(v:any)=>{const n=Number(v);return Number.isFinite(n)?n:null}
const tags=(kind:string,character:string)=>{const v=(kind+' '+character).toLocaleLowerCase('cs-CZ');const a:string[]=[];if(v.includes('hrad'))a.push('Hrad');if(v.includes('zřícen'))a.push('Zřícenina');if(v.includes('tvrz'))a.push('Tvrz');if(v.includes('zámek'))a.push('Zámek');if(v.includes('klášter')||v.includes('komenda'))a.push('Klášter');if(v.includes('opevně'))a.push('Opevněné místo');return [...new Set(a)]}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});if(req.method!=='POST')return json({ok:true,service:'hradnik-admin'});let body:any;try{body=await req.json()}catch{return json({error:'Neplatné JSON.'},400)};const me=await user(req);if(!me)return json({error:'Přístup mají jen administrátoři.'},403);try{
 if(body.action==='me')return json({ok:true,user:{id:me.id,username:me.username,display_name:me.display_name,role:me.role}})
 if(body.action==='list'){const {data,error}=await db.from('hradnik_places').select('id,name,kind,character,district,region,municipality,latitude,longitude,description,official_url,ticket_url,opening_hours,ticket_prices,photo_urls,source_url,admin_deleted,is_visible,is_current,source_count,kind_tags').order('name').range(0,9999);if(error)throw error;return json({ok:true,places:data||[]})}
 if(body.action==='save'){const id=body.id?Number(body.id):null;const name=text(body.name);const kind=text(body.kind)||'Hrad';if(!name)return json({error:'Název je povinný.'},400);const character=text(body.character);const row:any={name,kind,character:character||null,district:text(body.district)||null,region:text(body.region)||null,municipality:text(body.municipality)||null,latitude:num(body.latitude),longitude:num(body.longitude),description:text(body.description)||null,official_url:text(body.official_url)||null,ticket_url:text(body.ticket_url)||null,opening_hours:body.opening_hours||{},ticket_prices:body.ticket_prices||{},photo_urls:Array.isArray(body.photo_urls)?body.photo_urls:[],last_verified_at:new Date().toISOString(),updated_at:new Date().toISOString(),kind_tags:tags(kind,character)};if(id){const {data,error}=await db.from('hradnik_places').update(row).eq('id',id).select('*').single();if(error)throw error;return json({ok:true,place:data})}const ext='admin-'+crypto.randomUUID();const canonical='admin:'+crypto.randomUUID();const slug=name.toLocaleLowerCase('cs-CZ').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,160);const {data,error}=await db.from('hradnik_places').insert({...row,source_key:'admin',external_id:ext,slug,canonical_key:canonical,normalized_name:name.toLocaleLowerCase('cs-CZ'),primary_source_key:'admin',source_count:0,is_visible:true,is_current:true,admin_deleted:false}).select('*').single();if(error)throw error;const sourceRes=await db.from('hradnik_place_sources').insert({place_id:data.id,source_key:'admin',external_id:ext,source_url:'https://hradnik.vercel.app/',source_label:'Ruční úprava administrátorem',fetched_at:new Date().toISOString(),confidence:1,raw_data:{created_by:me.username},is_active:true});if(sourceRes.error)console.error(sourceRes.error);await db.from('hradnik_places').update({source_count:1}).eq('id',data.id);return json({ok:true,place:{...data,source_count:1}})}
 if(body.action==='delete'){const id=Number(body.id);if(!Number.isSafeInteger(id))return json({error:'Neplatná památka.'},400);const {data,error}=await db.from('hradnik_places').update({admin_deleted:true,is_visible:false,is_current:false,updated_at:new Date().toISOString()}).eq('id',id).select('id,name').single();if(error)throw error;await db.from('hradnik_place_sources').update({is_active:false}).eq('place_id',id);return json({ok:true,place:data})}
 if(body.action==='restore'){const id=Number(body.id);if(!Number.isSafeInteger(id))return json({error:'Neplatná památka.'},400);const {data,error}=await db.from('hradnik_places').update({admin_deleted:false,is_visible:true,is_current:true,updated_at:new Date().toISOString()}).eq('id',id).select('*').single();if(error)throw error;await db.from('hradnik_place_sources').update({is_active:true}).eq('place_id',id);return json({ok:true,place:data})}
 return json({error:'Neznámá akce.'},400)
}catch(e){console.error(e);return json({error:'Interní chyba adminu.'},500)}})
