const QUALITY_URL='https://cgshssdjgzzuprlwnabl.supabase.co/functions/v1/hradnik-quality'
const qtoken=()=>localStorage.getItem('hradnik_session')||''
const qesc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const qheaders=()=>({'Content-Type':'application/json',Authorization:`Bearer ${qtoken()}`})
async function qapi(action,body={}){const r=await fetch(QUALITY_URL,{method:'POST',headers:qheaders(),body:JSON.stringify({action,...body})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Operaci se nepodařilo dokončit.');return d}
function qstyle(){if(document.getElementById('hradnik-quality-style'))return;const s=document.createElement('style');s.id='hradnik-quality-style';s.textContent=`.hq-panel{width:min(980px,100%);max-height:94dvh;overflow:hidden;background:#f6f7fb;border-radius:24px;box-shadow:0 30px 120px #0007;display:flex;flex-direction:column}.hq-head{display:flex;justify-content:space-between;align-items:center;padding:16px 18px;background:#fff;border-bottom:1px solid #e3e6ee}.hq-title{margin:0;font-size:20px}.hq-sub{font-size:12px;color:#737b8b;margin-top:2px}.hq-body{overflow:auto;padding:12px}.hq-summary{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:10px}.hq-pill{padding:7px 10px;border-radius:999px;background:#eeeafd;color:#5e46cf;font-weight:800;font-size:12px}.hq-list{display:grid;gap:8px}.hq-row{display:flex;align-items:center;gap:12px;background:#fff;border:1px solid #e3e6ee;border-radius:15px;padding:11px}.hq-main{flex:1;min-width:0}.hq-main b{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.hq-main small{display:block;color:#737b8b;margin-top:3px}.hq-score{width:44px;height:44px;border-radius:50%;display:grid;place-items:center;font-weight:900;background:#fff4db;color:#745d1b;border:3px solid #f0c765}.hq-actions{display:flex;gap:6px}.hq-actions button{min-height:38px;padding:8px 10px}.hq-ok{background:#e8f7ef!important;color:#16663f!important;border:1px solid #bfe5cf!important}.hq-no{background:#fff0f0!important;color:#a22!important;border:1px solid #edcaca!important}@media(max-width:560px){.hq-panel{width:100%;height:100%;max-height:none;border-radius:0}.hq-row{align-items:flex-start;flex-wrap:wrap}.hq-score{flex:0 0 44px}.hq-actions{width:100%;margin-left:56px}.hq-actions button{flex:1}}`;document.head.appendChild(s)}
function addQualityButton(){const t=document.querySelector('.hradnik-admin-toolbar');if(!t||t.querySelector('#hqOpen'))return false;const b=document.createElement('button');b.id='hqOpen';b.textContent='✅ Kontrola kvality';b.title='Zkontrolovat neověřené památky';b.onclick=()=>openQuality();t.appendChild(b);return true}
async function openQuality(){qstyle();document.querySelector('#hqModal')?.remove();const back=document.createElement('div');back.id='hqModal';back.className='hradnik-admin-backdrop';back.innerHTML=`<div class="hq-panel"><div class="hq-head"><div><h2 class="hq-title">✅ Kontrola kvality</h2><div class="hq-sub">Památky, které automatika zatím neumí spolehlivě potvrdit</div></div><button id="hqClose">✕</button></div><div class="hq-body"><div id="hqSummary" class="hq-summary"><span class="hq-pill">Načítám…</span></div><div id="hqList" class="hq-list"><div class="hradnik-admin-empty">Načítám…</div></div></div></div>`;document.body.appendChild(back);back.querySelector('#hqClose').onclick=()=>back.remove();back.addEventListener('click',e=>{if(e.target===back)back.remove()});await loadQuality()}
async function loadQuality(){const list=document.querySelector('#hqList'),sum=document.querySelector('#hqSummary');if(!list)return;try{const d=await qapi('list');const rows=d.places||[];sum.innerHTML=`<span class="hq-pill">${rows.length.toLocaleString('cs-CZ')} ke kontrole</span>`;if(!rows.length){list.innerHTML='<div class="hradnik-admin-empty">🎉 Nic není potřeba kontrolovat.</div>';return}list.innerHTML=rows.map(p=>`<div class="hq-row"><div class="hq-score">${Number(p.quality_score||0)}</div><div class="hq-main"><b>${qesc(p.name)}</b><small>${qesc(p.kind||'')} · ${qesc(p.municipality||p.district||p.region||'')} · ${qesc(p.quality_reason||'K ověření')}</small></div><div class="hq-actions"><button class="hq-ok" data-ok="${p.id}">✓ Potvrdit</button><button class="hq-no" data-no="${p.id}">✕ Zamítnout</button></div></div>`).join('');list.querySelectorAll('[data-ok]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await qapi('approve',{id:Number(b.dataset.ok)});await loadQuality()}catch(e){alert(e.message);b.disabled=false}});list.querySelectorAll('[data-no]').forEach(b=>b.onclick=async()=>{const reason=prompt('Důvod zamítnutí:','Nejde o samostatnou historickou památku');if(reason===null)return;b.disabled=true;try{await qapi('reject',{id:Number(b.dataset.no),reason});await loadQuality()}catch(e){alert(e.message);b.disabled=false}})}catch(e){list.innerHTML=`<div class="hradnik-admin-empty">${qesc(e.message)}</div>`}}
new MutationObserver(()=>addQualityButton()).observe(document.body,{childList:true,subtree:true});addQualityButton()
