const NAV_LABELS=['Mapa','Seznam','Oblíbené','Kategorie','O aplikaci']
const NAV_ICONS=['map','list','favorites','nav-grid','nav-info']
const iconForKind=kind=>{const k=String(kind||'').toLocaleLowerCase('cs-CZ');if(k.includes('zřícenina')||k.includes('ruina')||k.includes('pozůstat'))return'/icons/ruin.svg';if(k.includes('zámek'))return'/icons/chateau.svg';if(k.includes('tvrz'))return'/icons/fortress.svg';if(k.includes('klášter'))return'/icons/monastery.svg';return'/icons/home.svg'}
let observer=null,applying=false,applyQueued=false

function buildSidebar(app,nav){if(!nav)return;let side=app.querySelector('.redesign-sidebar');if(!side){side=document.createElement('aside');side.className='redesign-sidebar';const foot=document.createElement('div');foot.className='redesign-side-footer';foot.innerHTML='<div>Objevuj.<br>Poznávej.<br>Chraň.</div>';side.append(foot);app.insertBefore(side,app.firstChild)}const footer=side.querySelector('.redesign-side-footer');if(nav.parentElement!==side)side.insertBefore(nav,footer);nav.classList.add('redesign-nav');nav.querySelectorAll('button').forEach((b,i)=>{b.textContent='';b.dataset.redesignReady='1';let img=b.querySelector('img[data-redesign-icon]');if(!img){img=document.createElement('img');img.dataset.redesignIcon='1';b.appendChild(img)}img.src=`/icons/${NAV_ICONS[i]||'home'}.svg`;let text=b.querySelector('span[data-redesign-label]');if(!text){text=document.createElement('span');text.dataset.redesignLabel='1';b.appendChild(text)}text.textContent=NAV_LABELS[i]||''})}
function beautifyPlaces(){document.querySelectorAll('.placeIcon').forEach(node=>{if(node.dataset.redesigned==='1')return;const kind=node.parentElement?.querySelector('.placeCopy small')?.textContent?.split('·')[0]?.trim()||'';node.textContent='';const img=document.createElement('img');img.src=iconForKind(kind);img.alt='';node.appendChild(img);node.dataset.redesigned='1'})}
function enhanceMap(){const map=document.querySelector('#map');if(!map||map.parentElement?.classList.contains('map-layout'))return;const parent=map.parentElement;if(!parent)return;const layout=document.createElement('div');layout.className='map-layout';parent.insertBefore(layout,map);layout.append(map);const panel=document.createElement('aside');panel.className='map-focus-card';panel.innerHTML='<div class="focus-placeholder"><strong>Vyber památku na mapě</strong><br><span>Detail se otevře přímo vedle mapy.</span></div>';layout.append(panel);requestAnimationFrame(()=>window.dispatchEvent(new Event('resize')))}
function polishPage(){const main=document.querySelector('main.wrap');if(!main)return;main.classList.add('redesign-main');beautifyPlaces();enhanceMap()}
function apply(){if(applying)return;applying=true;observer?.disconnect();try{const app=document.querySelector('#app');if(!app)return;const nav=app.querySelector('#nav');if(nav)buildSidebar(app,nav);polishPage()}finally{applying=false;const app=document.querySelector('#app');if(app)observer?.observe(app,{childList:true,subtree:true})}}
function scheduleApply(){if(applyQueued)return;applyQueued=true;queueMicrotask(()=>{applyQueued=false;apply()})}observer=new MutationObserver(scheduleApply);const start=()=>{const app=document.querySelector('#app');if(!app)return;observer.observe(app,{childList:true,subtree:true});apply()};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start()
