-- Hradník standalone baseline
-- Captured from the live standalone Supabase project abqiprdggptuxebhpfyi on 2026-10-03.
-- Purpose: make a fresh Hradník database reproducible from this repository.
-- No production users, sessions, passwords, sync keys or other secrets are embedded here.
-- This baseline supersedes the older Domácnost+-era migrations that used household_members/hradnik_place_state.

create extension if not exists pgcrypto with schema extensions;
create extension if not exists pg_trgm with schema extensions;

create table if not exists public.hradnik_sources (
  id bigint generated by default as identity primary key,
  source_key text not null unique,
  name text not null,
  base_url text not null,
  enabled boolean not null default true,
  priority integer not null default 100,
  last_success_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.hradnik_places (
  id bigint generated by default as identity primary key,
  source_key text not null default 'seed',
  external_id text,
  slug text not null,
  name text not null,
  kind text not null check (kind = any (array['Hrad'::text,'Zámek'::text,'Zřícenina'::text,'Tvrz'::text,'Klášter'::text,'Opevněné místo'::text,'Jiné dochované místo'::text])),
  character text,
  district text,
  region text,
  municipality text,
  latitude double precision,
  longitude double precision,
  description text,
  official_url text,
  ticket_url text,
  opening_hours jsonb not null default '{}'::jsonb,
  ticket_prices jsonb not null default '{}'::jsonb,
  photo_urls jsonb not null default '[]'::jsonb,
  source_url text,
  source_updated_at timestamptz,
  last_verified_at timestamptz,
  is_visible boolean not null default true,
  is_current boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  canonical_key text,
  normalized_name text,
  npu_id text,
  wikidata_id text,
  osm_id text,
  primary_source_key text,
  source_count integer not null default 0,
  kind_tags text[] not null default '{}'::text[],
  dedupe_key text,
  photo_credit text,
  photo_license text,
  photo_source_url text,
  admin_deleted boolean not null default false,
  info_summary text,
  info_source text,
  info_source_url text,
  info_updated_at timestamptz,
  info_status text not null default 'pending',
  info_confidence numeric,
  quality_status text not null default 'unreviewed',
  quality_reason text,
  quality_score integer not null default 0,
  quality_checked_at timestamptz
);

create table if not exists public.hradnik_place_sources (
  id bigint generated by default as identity primary key,
  place_id bigint not null references public.hradnik_places(id) on delete cascade,
  source_key text not null references public.hradnik_sources(source_key) on delete cascade,
  source_url text not null,
  source_label text,
  fetched_at timestamptz not null default now(),
  confidence numeric check (confidence >= 0 and confidence <= 1),
  external_id text,
  source_updated_at timestamptz,
  raw_data jsonb not null default '{}'::jsonb,
  is_active boolean not null default true
);

create table if not exists public.hradnik_sync_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null default 'running' check (status = any (array['running'::text,'success'::text,'partial'::text,'failed'::text])),
  discovered integer not null default 0,
  inserted_count integer not null default 0,
  updated_count integer not null default 0,
  hidden_count integer not null default 0,
  error_count integer not null default 0,
  sources jsonb not null default '[]'::jsonb,
  message text
);

create table if not exists public.hradnik_sync_control (
  id boolean primary key default true check (id = true),
  sync_key text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.hradnik_users (
  id uuid primary key default gen_random_uuid(),
  username text not null unique,
  password_hash text not null,
  display_name text,
  created_at timestamptz not null default now(),
  last_login_at timestamptz,
  role text not null default 'user' check (role = any (array['user'::text,'admin'::text]))
);

create table if not exists public.hradnik_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.hradnik_users(id) on delete cascade,
  token_hash text not null unique,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create table if not exists public.hradnik_user_place_state (
  user_id uuid not null references public.hradnik_users(id) on delete cascade,
  place_id bigint not null references public.hradnik_places(id) on delete cascade,
  status text not null default 'none' check (status = any (array['none'::text,'want'::text,'visited'::text])),
  favorite boolean not null default false,
  rating smallint not null default 0 check (rating >= 0 and rating <= 5),
  visited_on date,
  note text,
  updated_at timestamptz not null default now(),
  primary key (user_id, place_id)
);

create table if not exists public.hradnik_enrich_control (
  id boolean primary key default true,
  enrich_key text not null default md5((random())::text || (clock_timestamp())::text),
  updated_at timestamptz not null default now()
);

create index if not exists hradnik_place_sources_place_active_idx on public.hradnik_place_sources(place_id,is_active);
create index if not exists hradnik_place_sources_place_idx on public.hradnik_place_sources(place_id);
create unique index if not exists hradnik_place_sources_source_external_uq on public.hradnik_place_sources(source_key,external_id);

create index if not exists hradnik_places_admin_deleted_idx on public.hradnik_places(admin_deleted);
create unique index if not exists hradnik_places_canonical_key_uq on public.hradnik_places(canonical_key) where canonical_key is not null;
create index if not exists hradnik_places_dedupe_key_idx on public.hradnik_places(dedupe_key);
create index if not exists hradnik_places_geo_idx on public.hradnik_places(latitude,longitude) where latitude is not null and longitude is not null;
create index if not exists hradnik_places_gps_idx on public.hradnik_places(latitude,longitude);
create index if not exists hradnik_places_info_pending_idx on public.hradnik_places(info_status,id) where is_visible=true and is_current=true;
create index if not exists hradnik_places_info_status_updated_idx on public.hradnik_places(info_status,info_updated_at);
create index if not exists hradnik_places_kind_idx on public.hradnik_places(kind);
create index if not exists hradnik_places_kind_tags_gin_idx on public.hradnik_places using gin(kind_tags);
create index if not exists hradnik_places_normalized_name_idx on public.hradnik_places using gin(normalized_name extensions.gin_trgm_ops);
create index if not exists hradnik_places_npu_id_idx on public.hradnik_places(npu_id) where npu_id is not null;
create index if not exists hradnik_places_osm_id_idx on public.hradnik_places(osm_id) where osm_id is not null;
create index if not exists hradnik_places_quality_score_idx on public.hradnik_places(quality_score);
create index if not exists hradnik_places_quality_status_idx on public.hradnik_places(quality_status);
create index if not exists hradnik_places_region_idx on public.hradnik_places(region);
create unique index if not exists hradnik_places_source_external_uq on public.hradnik_places(source_key,external_id);
create index if not exists hradnik_places_visible_kind_idx on public.hradnik_places(is_visible,kind);
create index if not exists hradnik_places_wikidata_id_idx on public.hradnik_places(wikidata_id) where wikidata_id is not null;

create index if not exists hradnik_sessions_expires_idx on public.hradnik_sessions(expires_at);
create index if not exists hradnik_sessions_token_hash_idx on public.hradnik_sessions(token_hash);
create index if not exists hradnik_sessions_user_id_idx on public.hradnik_sessions(user_id);
create index if not exists hradnik_user_place_state_place_idx on public.hradnik_user_place_state(place_id);
create index if not exists hradnik_user_place_state_user_idx on public.hradnik_user_place_state(user_id);
create index if not exists hradnik_users_role_idx on public.hradnik_users(role);

create or replace function public.hradnik_normalize_name(p_name text)
returns text
language sql
immutable set search_path = public, extensions
as $function$ select regexp_replace(translate(lower(trim(coalesce(p_name,''))),'áčďéěíňóřšťúůýž','acdeeinorstuuyz'),'[^a-z0-9]+',' ','g'); $function$;

create or replace function public.hradnik_dedupe_key(p_name text)
returns text
language sql
immutable set search_path = public, extensions
as $function$
  select trim(regexp_replace(
    regexp_replace(
      regexp_replace(
        regexp_replace(public.hradnik_normalize_name(coalesce(p_name,'')),
          '^(terenni pozustatky po|pozustatky po)( mozny| mozna| mozne)?[[:space:]]+',' ','i'),
        '(zricenina hradu|zricenina tvrze|zanikly hrad|zanikla tvrz|hrad prestaveny na zamek)$',' ','i'),
      '^(hrad|zamek|zricenina|tvrz|klaster|pevnost|opevnene misto)[[:space:]]+',' ','i'),
    '[[:space:]]+(hrad|zamek|zricenina|tvrz|klaster|pevnost)$',' ','i'));
$function$;

create or replace function public.hradnik_extract_kind_tags(p_character text, p_kind text)
returns text[]
language plpgsql
immutable set search_path = public, extensions
as $function$
declare
  v text := lower(coalesce(p_character,'') || ' ' || coalesce(p_kind,''));
  out text[] := array[]::text[];
begin
  if v like '%zřícen%' or v like '%zricen%' or v like '%ruin%' then out := array_append(out,'Zřícenina'); end if;
  if v like '%tvrz%' or v like '%fort%' then out := array_append(out,'Tvrz'); end if;
  if v like '%klášter%' or v like '%klaster%' or v like '%komenda%' or v like '%monastery%' or v like '%abbey%' then out := array_append(out,'Klášter'); end if;
  if v like '%zámek%' or v like '%zamek%' or v like '%chateau%' or v like '%manor%' then out := array_append(out,'Zámek'); end if;
  if v like '%hrad%' or v like '%castle%' then out := array_append(out,'Hrad'); end if;
  if v like '%opevně%' or v like '%opevnene%' or v like '%bašta%' or v like '%basta%' or v like '%věž%' or v like '%vez%' or v like '%fort%' then out := array_append(out,'Opevněné místo'); end if;
  if coalesce(array_length(out,1),0)=0 and nullif(p_kind,'') is not null then out := array_append(out,p_kind); end if;
  return (select array_agg(distinct x order by x) from unnest(out) x);
end;
$function$;

create or replace function public.hradnik_quality_ok(p text)
returns boolean
language sql
immutable set search_path = public, extensions
as $function$ select coalesce(position(chr(65533) in coalesce(p,''))=0,true); $function$;

create or replace function public.hradnik_force_ruin_kind()
returns trigger
language plpgsql
set search_path = public, extensions
as $function$
declare c text := lower(coalesce(new.character,'')); n text := lower(coalesce(new.name,''));
begin
  if new.kind='Hrad' and (n ~ '(zřícen|zricen|ruin|trosk)' or c ~ '(zřícen|zricen|ruin|trosk)' or c ~ 'castle rem' or c='castle yes' or c ~ 'pozůstatky po .*hradu') then new.kind:='Zřícenina';
  elsif new.kind='Hrad' and (c='tvrz' or c ~ 'hrad/tvrz') then new.kind:='Tvrz';
  elsif new.kind='Hrad' and c ~ 'hrad \(komenda\)' then new.kind:='Klášter';
  elsif new.kind='Hrad' and c ~ 'opevněný kostel' then new.kind:='Opevněné místo';
  elsif new.kind='Hrad' and c ~ '(hrad.*přestavěn.*zámek|přestavěný hrad/zámek)' then new.kind:='Zámek';
  end if;
  return new;
end;
$function$;

create or replace function public.hradnik_quality_guard()
returns trigger
language plpgsql
set search_path = public, extensions
as $function$
declare n text := lower(coalesce(new.name,'')); src text := lower(coalesce(new.source_url,''));
begin
  if new.quality_status is distinct from 'approved' and new.quality_status is distinct from 'manual' then
    if n ~ '(úřad|urad|městský úřad|mestsky urad|ústav|ustav|institut|škola|skola|nemocnice|univerzita|restaurace|hotel|hřiště|hriste|parkoviště|parkoviste|nádraží|nadrazi|stanice|autobus|čerpací stanice|cerpaci stanice)' then
      if src like '%openstreetmap.org%' then new.quality_status:='rejected'; new.quality_reason:='OSM objekt vypadá jako běžná instituce, služba nebo infrastruktura, nikoli historická památka'; new.is_visible:=false; end if;
    end if;
    if src like '%openstreetmap.org%' and coalesce(nullif(trim(new.wikidata_id),''),'')='' and coalesce(nullif(trim(new.official_url),''),'')='' and n !~ '(hrad|zámek|zamek|tvrz|zřícen|zricen|fort|bastion|klášter|klaster|palác|palac|hradiště|hradiste|komenda|opevnění|opevneni|bašta|basta|brána|brana|věž|vez)' then
      new.quality_status:='rejected'; new.quality_reason:='OSM-only objekt bez doplňující identifikace nebo jasného označení historické památky'; new.is_visible:=false;
    end if;
  end if;
  if n ~ '(^|\s)(zámek|zamek)(\s|$)' then new.kind:='Zámek';
  elsif n ~ '(^|\s)tvrz(\s|$)' then new.kind:='Tvrz';
  elsif n ~ '(^|\s)(zřícenina|zricenina)(\s|$)' then new.kind:='Zřícenina';
  elsif n ~ '(^|\s)(klášter|klaster|komenda)(\s|$)' then new.kind:='Klášter';
  elsif n ~ '(^|\s)(fort|bastion|pevnost)(\s|$)' then new.kind:='Opevněné místo'; end if;
  return new;
end;
$function$;

create or replace function public.hradnik_admin_deleted_source_guard()
returns trigger
language plpgsql
security definer set search_path = public
as $function$ begin if new.place_id is not null and exists(select 1 from public.hradnik_places p where p.id=new.place_id and p.admin_deleted=true) then new.is_active:=false; end if; return new; end; $function$;

create or replace function public.hradnik_compute_quality()
returns trigger
language plpgsql
security definer set search_path = public
as $function$
declare n text := lower(coalesce(new.name,'')); score integer := 50; status text := 'needs_review'; reason text := 'Základní kontrola'; bad boolean := false; source_wd text := nullif(trim(coalesce(new.wikidata_id,'')),''); source_web text := nullif(trim(coalesce(new.official_url,'')),'');
begin
  if source_wd is null and new.id is not null then select nullif(trim(coalesce(s.raw_data->>'wikidata_id','')),'') into source_wd from public.hradnik_place_sources s where s.place_id=new.id and coalesce(s.is_active,true)=true and nullif(trim(coalesce(s.raw_data->>'wikidata_id','')),'') is not null order by coalesce(s.confidence,0) desc limit 1; end if;
  if source_web is null and new.id is not null then select nullif(trim(coalesce(s.raw_data->>'official_url','')),'') into source_web from public.hradnik_place_sources s where s.place_id=new.id and coalesce(s.is_active,true)=true and nullif(trim(coalesce(s.raw_data->>'official_url','')),'') is not null order by coalesce(s.confidence,0) desc limit 1; end if;
  if n='' or n ~ '[�]' then bad:=true; reason:='Chybějící nebo rozbité jméno'; end if;
  if n ~ '(úřad městské části|úřad|botanický ústav|nemocnice|poliklinika|základní škola|střední škola|obchodní centrum|supermarket|parkoviště|nádraží)' and n !~ '(hrad|zámek|tvrz|klášter|pevnost|fort|bastion)' then bad:=true; reason:='Pravděpodobně běžná budova nebo instituce'; end if;
  if n in ('hrad','zámek','tvrz','palác','klášter','pevnost','zřícenina','fort','bastion') and source_wd is null and source_web is null then bad:=true; score:=10; reason:='Příliš obecný název bez další identifikace'; end if;
  if source_wd is not null then score:=greatest(score,95); end if;
  if source_web is not null then score:=greatest(score,85); end if;
  if coalesce(new.source_url,'') ~* '(hrady\.cz|hrady-zriceniny\.cz|pamatkovykatalog\.cz)' then score:=greatest(score,88); end if;
  if coalesce(new.character,'') ~* '(castle|chateau|manor|fort|monastery|abbey|zřícen|tvrz|zámek|hrad|klášter)' then score:=greatest(score,60); end if;
  if coalesce(new.latitude,0) between 48 and 52 and coalesce(new.longitude,0) between 12 and 19 then score:=least(100,score+5); end if;
  if coalesce(new.description,'')<>'' or coalesce(new.info_summary,'')<>'' then score:=least(100,score+5); end if;
  if bad then status:='rejected'; score:=least(score,10); else status:=case when score>=90 then 'verified' when score>=75 then 'probable' else 'needs_review' end; end if;
  new.quality_score:=score; new.quality_status:=status; new.quality_reason:=reason; new.quality_checked_at:=now();
  if status='rejected' and coalesce(new.admin_deleted,false)=false then new.is_visible:=false; end if;
  return new;
end;
$function$;

create or replace function public.hradnik_refresh_place_quality_from_source()
returns trigger
language plpgsql
security definer set search_path = public
as $function$ begin update public.hradnik_places set updated_at=now() where id=new.place_id; return new; end; $function$;

create or replace function public.hradnik_ingest_source_records(p_records jsonb)
returns jsonb
language plpgsql
security definer set search_path = public
as $function$
declare
  r jsonb; v_source text; v_external text; v_name text; v_kind text; v_character text;
  v_npu text; v_wikidata text; v_osm text; v_lat double precision; v_lon double precision;
  v_district text; v_region text; v_municipality text; v_description text; v_official text; v_ticket text;
  v_opening jsonb; v_prices jsonb; v_photos jsonb; v_source_url text; v_source_updated timestamptz;
  v_place_id bigint; v_norm text; v_dedupe text; v_tags text[]; v_inserted int:=0; v_updated int:=0; v_linked int:=0; v_skipped int:=0;
begin
  if p_records is null or jsonb_typeof(p_records)<>'array' then return jsonb_build_object('ok',false,'error','p_records must be a JSON array'); end if;
  for r in select value from jsonb_array_elements(p_records) loop
    v_source:=nullif(trim(r->>'source_key'),''); v_external:=nullif(trim(r->>'external_id'),''); v_name:=nullif(trim(r->>'name'),''); v_kind:=nullif(trim(r->>'kind'),''); v_character:=nullif(trim(r->>'character'),'');
    if v_name is null or v_name like '%�%' or coalesce(v_character,'') like '%�%' or coalesce(r->>'description','') like '%�%' then v_skipped:=v_skipped+1; continue; end if;
    v_npu:=nullif(trim(r->>'npu_id'),''); v_wikidata:=nullif(trim(r->>'wikidata_id'),''); v_osm:=nullif(trim(r->>'osm_id'),'');
    v_lat:=case when nullif(r->>'latitude','') is null then null else (r->>'latitude')::double precision end; v_lon:=case when nullif(r->>'longitude','') is null then null else (r->>'longitude')::double precision end;
    v_district:=nullif(trim(r->>'district'),''); v_region:=nullif(trim(r->>'region'),''); v_municipality:=nullif(trim(r->>'municipality'),'');
    v_description:=nullif(trim(r->>'description'),''); v_official:=nullif(trim(r->>'official_url'),''); v_ticket:=nullif(trim(r->>'ticket_url'),'');
    v_opening:=coalesce(r->'opening_hours','{}'::jsonb); v_prices:=coalesce(r->'ticket_prices','{}'::jsonb); v_photos:=coalesce(r->'photo_urls','[]'::jsonb); v_source_url:=nullif(trim(r->>'source_url'),'');
    v_source_updated:=case when nullif(r->>'source_updated_at','') is null then null else (r->>'source_updated_at')::timestamptz end;
    if v_source is null or v_external is null then continue; end if;
    v_norm:=public.hradnik_normalize_name(v_name); v_dedupe:=public.hradnik_dedupe_key(v_name); v_tags:=public.hradnik_extract_kind_tags(v_character,v_kind); v_place_id:=null;
    if v_wikidata is not null then select id into v_place_id from public.hradnik_places where wikidata_id=v_wikidata order by id limit 1; end if;
    if v_place_id is null and v_npu is not null then select id into v_place_id from public.hradnik_places where npu_id=v_npu order by id limit 1; end if;
    if v_place_id is null and v_osm is not null then select id into v_place_id from public.hradnik_places where osm_id=v_osm order by id limit 1; end if;
    if v_place_id is null then select place_id into v_place_id from public.hradnik_place_sources where source_key=v_source and external_id=v_external order by id desc limit 1; end if;
    if v_place_id is null and v_dedupe<>'' then select p.id into v_place_id from public.hradnik_places p where p.is_current and p.dedupe_key=v_dedupe and ((v_district is not null and p.district is not null and public.hradnik_normalize_name(p.district)=public.hradnik_normalize_name(v_district)) or (v_region is not null and p.region is not null and public.hradnik_normalize_name(p.region)=public.hradnik_normalize_name(v_region))) order by (p.wikidata_id is not null) desc,(p.osm_id is not null) desc,p.source_count desc,p.id limit 1; end if;
    if v_place_id is null and v_lat is not null and v_lon is not null then select p.id into v_place_id from public.hradnik_places p where p.is_current and p.dedupe_key=v_dedupe and p.latitude is not null and p.longitude is not null and abs(p.latitude-v_lat)<=0.008 and abs((p.longitude-v_lon)*cos(radians((p.latitude+v_lat)/2)))<=0.012 order by p.source_count desc,p.id limit 1; end if;
    if v_place_id is null then
      insert into public.hradnik_places(canonical_key,source_key,external_id,slug,name,kind,character,district,region,municipality,latitude,longitude,description,official_url,ticket_url,opening_hours,ticket_prices,photo_urls,source_url,source_updated_at,last_verified_at,normalized_name,primary_source_key,source_count,is_visible,is_current,kind_tags,dedupe_key)
      values('auto:'||md5(v_source||':'||v_external||':'||v_dedupe),v_source,v_external,regexp_replace(v_dedupe,' ','-','g'),v_name,coalesce(v_kind,'Jiné dochované místo'),v_character,v_district,v_region,v_municipality,v_lat,v_lon,v_description,v_official,v_ticket,v_opening,v_prices,v_photos,v_source_url,v_source_updated,coalesce(v_source_updated,now()),v_norm,v_source,0,true,true,v_tags,v_dedupe) returning id into v_place_id; v_inserted:=v_inserted+1;
    else
      update public.hradnik_places p set name=case when p.name like '%�%' or length(coalesce(v_name,''))>length(coalesce(p.name,'')) then v_name else p.name end, kind=case when v_source='hrady_zriceniny' and lower(coalesce(v_character,'')) ~ '(zřícen|ruins? castle)' then 'Zřícenina' when p.kind is null or p.kind='Jiné dochované místo' then coalesce(v_kind,p.kind) else p.kind end, character=case when p.character like '%�%' or (p.character is null and v_character is not null) then v_character else p.character end, district=coalesce(p.district,v_district),region=coalesce(p.region,v_region),municipality=coalesce(p.municipality,v_municipality),latitude=coalesce(p.latitude,v_lat),longitude=coalesce(p.longitude,v_lon),description=case when p.description like '%�%' or p.description is null then v_description else p.description end,official_url=coalesce(p.official_url,v_official),ticket_url=coalesce(p.ticket_url,v_ticket),opening_hours=case when p.opening_hours='{}'::jsonb then v_opening else p.opening_hours end,ticket_prices=case when p.ticket_prices='{}'::jsonb then v_prices else p.ticket_prices end,photo_urls=case when p.photo_urls='[]'::jsonb then v_photos else p.photo_urls end,npu_id=coalesce(p.npu_id,v_npu),wikidata_id=coalesce(p.wikidata_id,v_wikidata),osm_id=coalesce(p.osm_id,v_osm),normalized_name=public.hradnik_normalize_name(case when p.name like '%�%' then v_name else p.name end),dedupe_key=public.hradnik_dedupe_key(case when p.name like '%�%' then v_name else p.name end),kind_tags=(select array_agg(distinct x order by x) from unnest(coalesce(p.kind_tags,'{}'::text[])||coalesce(v_tags,'{}'::text[])) x),source_updated_at=coalesce(v_source_updated,p.source_updated_at),last_verified_at=greatest(coalesce(p.last_verified_at,'epoch'::timestamptz),coalesce(v_source_updated,now())),updated_at=now() where p.id=v_place_id; v_updated:=v_updated+1;
    end if;
    insert into public.hradnik_place_sources(place_id,source_key,external_id,source_url,source_label,fetched_at,source_updated_at,confidence,raw_data,is_active)
    values(v_place_id,v_source,v_external,v_source_url,coalesce((select name from public.hradnik_sources where source_key=v_source),v_source),now(),v_source_updated,1.0,r,true)
    on conflict (source_key,external_id) do update set place_id=excluded.place_id,source_url=coalesce(excluded.source_url,public.hradnik_place_sources.source_url),source_updated_at=excluded.source_updated_at,fetched_at=now(),raw_data=excluded.raw_data,is_active=true,confidence=greatest(coalesce(public.hradnik_place_sources.confidence,0),coalesce(excluded.confidence,0)); v_linked:=v_linked+1;
  end loop;
  update public.hradnik_places p set source_count=(select count(*) from public.hradnik_place_sources s where s.place_id=p.id and s.is_active=true) where p.is_current=true;
  return jsonb_build_object('ok',true,'inserted',v_inserted,'updated',v_updated,'linked',v_linked,'skipped',v_skipped);
end;
$function$;

create or replace function public.hradnik_auto_dedupe()
returns jsonb
language plpgsql
security definer set search_path = public
as $function$
declare r record; merged int:=0; keep_id bigint; drop_id bigint;
begin
  for r in
    select a.id a_id,b.id b_id
    from public.hradnik_places a join public.hradnik_places b on a.id<b.id and a.is_current and b.is_current
      and coalesce(a.dedupe_key,public.hradnik_dedupe_key(a.name))=coalesce(b.dedupe_key,public.hradnik_dedupe_key(b.name))
      and a.latitude is not null and b.latitude is not null and a.longitude is not null and b.longitude is not null
      and abs(a.latitude-b.latitude)<=0.012
      and abs((a.longitude-b.longitude)*cos(radians((a.latitude+b.latitude)/2)))<=0.018
  loop
    begin
      select case when a.source_key='seed' then b.id when b.source_key='seed' then a.id when coalesce(b.source_count,0)>coalesce(a.source_count,0) then b.id when coalesce(a.wikidata_id,'')='' and coalesce(b.wikidata_id,'')<>'' then b.id else a.id end into keep_id from public.hradnik_places a, public.hradnik_places b where a.id=r.a_id and b.id=r.b_id;
      drop_id:=case when keep_id=r.a_id then r.b_id else r.a_id end;
      insert into public.hradnik_place_sources(place_id,source_key,external_id,source_url,source_label,fetched_at,source_updated_at,confidence,raw_data,is_active)
        select keep_id,source_key,external_id,source_url,source_label,fetched_at,source_updated_at,confidence,raw_data,is_active from public.hradnik_place_sources where place_id=drop_id
        on conflict (source_key,external_id) do update set place_id=excluded.place_id,source_url=coalesce(excluded.source_url,public.hradnik_place_sources.source_url),raw_data=coalesce(excluded.raw_data,public.hradnik_place_sources.raw_data),is_active=excluded.is_active;
      delete from public.hradnik_place_sources where place_id=drop_id;
      insert into public.hradnik_user_place_state(user_id,place_id,status,favorite,rating,visited_on,note,updated_at)
        select user_id,keep_id,status,favorite,rating,visited_on,note,updated_at from public.hradnik_user_place_state where place_id=drop_id
        on conflict (user_id,place_id) do update set status=case when excluded.status='visited' or public.hradnik_user_place_state.status='visited' then 'visited' when excluded.status='want' or public.hradnik_user_place_state.status='want' then 'want' else 'none' end,favorite=public.hradnik_user_place_state.favorite or excluded.favorite,rating=greatest(coalesce(public.hradnik_user_place_state.rating,0),coalesce(excluded.rating,0)),visited_on=coalesce(public.hradnik_user_place_state.visited_on,excluded.visited_on),note=coalesce(nullif(public.hradnik_user_place_state.note,''),excluded.note),updated_at=greatest(public.hradnik_user_place_state.updated_at,excluded.updated_at);
      delete from public.hradnik_user_place_state where place_id=drop_id;
      update public.hradnik_places p set npu_id=coalesce(p.npu_id,d.npu_id),wikidata_id=coalesce(p.wikidata_id,d.wikidata_id),osm_id=coalesce(p.osm_id,d.osm_id),latitude=coalesce(p.latitude,d.latitude),longitude=coalesce(p.longitude,d.longitude),municipality=coalesce(p.municipality,d.municipality),district=coalesce(p.district,d.district),region=coalesce(p.region,d.region),description=coalesce(p.description,d.description),official_url=coalesce(p.official_url,d.official_url),ticket_url=coalesce(p.ticket_url,d.ticket_url),photo_urls=case when jsonb_array_length(coalesce(p.photo_urls,'[]'::jsonb))=0 then d.photo_urls else p.photo_urls end,photo_credit=coalesce(p.photo_credit,d.photo_credit),photo_license=coalesce(p.photo_license,d.photo_license),photo_source_url=coalesce(p.photo_source_url,d.photo_source_url),source_count=(select count(*) from public.hradnik_place_sources s where s.place_id=keep_id and s.is_active),updated_at=now() from public.hradnik_places d where p.id=keep_id and d.id=drop_id;
      update public.hradnik_places set is_current=false,is_visible=false,updated_at=now() where id=drop_id;
      merged:=merged+1;
    exception when others then continue; end;
  end loop;
  return jsonb_build_object('merged',merged);
end;
$function$;

create or replace function public.hradnik_auto_dedupe_v3()
returns integer
language plpgsql
security definer set search_path = public
as $function$ declare j jsonb; begin j:=public.hradnik_auto_dedupe(); return coalesce((j->>'merged')::integer,0); end; $function$;

create or replace function public.hradnik_merge_obvious_duplicates()
returns integer
language plpgsql
security definer set search_path = public
as $function$ declare j jsonb; begin j:=public.hradnik_auto_dedupe(); return coalesce((j->>'merged')::integer,0); end; $function$;

create or replace function public.hradnik_requeue_fallbacks()
returns integer
language plpgsql
security definer set search_path = public
as $function$ declare n integer; begin with x as (update public.hradnik_places set info_status='pending',updated_at=now() where is_visible=true and is_current=true and info_status='fallback' and (info_updated_at is null or info_updated_at<now()-interval '7 days') returning 1) select count(*) into n from x; return n; end; $function$;

drop trigger if exists hradnik_admin_deleted_source_guard on public.hradnik_place_sources;
create trigger hradnik_admin_deleted_source_guard
before insert or update on public.hradnik_place_sources
for each row execute function public.hradnik_admin_deleted_source_guard();

drop trigger if exists hradnik_quality_source_refresh on public.hradnik_place_sources;
create trigger hradnik_quality_source_refresh
after insert or update on public.hradnik_place_sources
for each row execute function public.hradnik_refresh_place_quality_from_source();

drop trigger if exists hradnik_quality_guard on public.hradnik_places;
create trigger hradnik_quality_guard
before insert or update on public.hradnik_places
for each row execute function public.hradnik_compute_quality();

drop trigger if exists trg_hradnik_force_ruin_kind on public.hradnik_places;
create trigger trg_hradnik_force_ruin_kind
before insert or update on public.hradnik_places
for each row execute function public.hradnik_force_ruin_kind();

drop trigger if exists trg_hradnik_quality_guard on public.hradnik_places;
create trigger trg_hradnik_quality_guard
before insert or update on public.hradnik_places
for each row execute function public.hradnik_quality_guard();

alter table public.hradnik_sources enable row level security;
alter table public.hradnik_places enable row level security;
alter table public.hradnik_place_sources enable row level security;
alter table public.hradnik_sync_runs enable row level security;
alter table public.hradnik_sync_control enable row level security;
alter table public.hradnik_users enable row level security;
alter table public.hradnik_sessions enable row level security;
alter table public.hradnik_user_place_state enable row level security;
alter table public.hradnik_enrich_control enable row level security;

drop policy if exists hradnik_sources_public_read on public.hradnik_sources;
create policy hradnik_sources_public_read on public.hradnik_sources
for select to anon, authenticated using (enabled=true);

drop policy if exists hradnik_places_public_read on public.hradnik_places;
create policy hradnik_places_public_read on public.hradnik_places
for select to anon, authenticated using (is_visible=true and is_current=true);

drop policy if exists hradnik_place_sources_public_read on public.hradnik_place_sources;
create policy hradnik_place_sources_public_read on public.hradnik_place_sources
for select to anon, authenticated using (true);

revoke all on table public.hradnik_sources, public.hradnik_places, public.hradnik_place_sources,
  public.hradnik_sync_runs, public.hradnik_sync_control, public.hradnik_users,
  public.hradnik_sessions, public.hradnik_user_place_state, public.hradnik_enrich_control
from anon, authenticated;

grant select on table public.hradnik_sources, public.hradnik_places, public.hradnik_place_sources to anon, authenticated;
grant all on table public.hradnik_sources, public.hradnik_places, public.hradnik_place_sources,
  public.hradnik_sync_runs, public.hradnik_sync_control, public.hradnik_users,
  public.hradnik_sessions, public.hradnik_user_place_state, public.hradnik_enrich_control
to service_role;
grant usage, select on all sequences in schema public to service_role;

revoke all on function public.hradnik_normalize_name(p_name text) from public, anon, authenticated;
grant execute on function public.hradnik_normalize_name(p_name text) to service_role;
revoke all on function public.hradnik_dedupe_key(p_name text) from public, anon, authenticated;
grant execute on function public.hradnik_dedupe_key(p_name text) to service_role;
revoke all on function public.hradnik_extract_kind_tags(p_character text, p_kind text) from public, anon, authenticated;
grant execute on function public.hradnik_extract_kind_tags(p_character text, p_kind text) to service_role;
revoke all on function public.hradnik_quality_ok(p text) from public, anon, authenticated;
grant execute on function public.hradnik_quality_ok(p text) to service_role;
revoke all on function public.hradnik_force_ruin_kind() from public, anon, authenticated;
grant execute on function public.hradnik_force_ruin_kind() to service_role;
revoke all on function public.hradnik_quality_guard() from public, anon, authenticated;
grant execute on function public.hradnik_quality_guard() to service_role;
revoke all on function public.hradnik_admin_deleted_source_guard() from public, anon, authenticated;
grant execute on function public.hradnik_admin_deleted_source_guard() to service_role;
revoke all on function public.hradnik_compute_quality() from public, anon, authenticated;
grant execute on function public.hradnik_compute_quality() to service_role;
revoke all on function public.hradnik_refresh_place_quality_from_source() from public, anon, authenticated;
grant execute on function public.hradnik_refresh_place_quality_from_source() to service_role;
revoke all on function public.hradnik_ingest_source_records(p_records jsonb) from public, anon, authenticated;
grant execute on function public.hradnik_ingest_source_records(p_records jsonb) to service_role;
revoke all on function public.hradnik_auto_dedupe() from public, anon, authenticated;
grant execute on function public.hradnik_auto_dedupe() to service_role;
revoke all on function public.hradnik_auto_dedupe_v3() from public, anon, authenticated;
grant execute on function public.hradnik_auto_dedupe_v3() to service_role;
revoke all on function public.hradnik_merge_obvious_duplicates() from public, anon, authenticated;
grant execute on function public.hradnik_merge_obvious_duplicates() to service_role;
revoke all on function public.hradnik_requeue_fallbacks() from public, anon, authenticated;
grant execute on function public.hradnik_requeue_fallbacks() to service_role;

insert into public.hradnik_sources(source_key,name,base_url,enabled,priority) values
  ('atlasceska','AtlasCeska.cz','https://www.atlasceska.cz/',true,45),
  ('turistika','Turistika.cz','https://www.turistika.cz/',true,50),
  ('kudyznudy','Kudy z nudy / CzechTourism','https://www.kudyznudy.cz/',true,60),
  ('hradycz','Hrady.cz','https://www.hrady.cz/',true,75),
  ('hrady_zriceniny','Hrady-zříceniny.cz','https://www.hrady-zriceniny.cz/',true,80),
  ('osm','OpenStreetMap','https://www.openstreetmap.org/',true,90),
  ('wikidata','Wikidata','https://www.wikidata.org/',true,95),
  ('npu','Národní památkový ústav – Památkový katalog','https://pamatkovykatalog.cz/',true,100),
  ('admin','Hradník – ruční úpravy','https://hradnik.vercel.app/',true,110)
on conflict (source_key) do update
set name=excluded.name,base_url=excluded.base_url,enabled=excluded.enabled,priority=excluded.priority,updated_at=now();

insert into public.hradnik_sync_control(id,sync_key)
values (true, encode(extensions.gen_random_bytes(32),'hex'))
on conflict (id) do nothing;

insert into public.hradnik_enrich_control(id)
values (true)
on conflict (id) do nothing;
